# Generated by Django 2.2.1 on 2020-07-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0002_shareride'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('from_place', models.CharField(max_length=50)),
                ('to_place', models.CharField(max_length=50)),
                ('flexible_timings', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(null=True)),
                ('start_date_time', models.DateTimeField(null=True)),
                ('end_date_time', models.DateTimeField(null=True)),
                ('no_of_assets', models.IntegerField()),
                ('asset_type', models.CharField(choices=[('PARCEL', 'PARCEL'), ('BAG', 'BAG'), ('FURNITURE', 'FURNITURE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('others', models.CharField(max_length=50)),
                ('asset_sensitivity', models.CharField(choices=[('SENSITIVITY', 'SENSITIVITY'), ('HIGHLY_SENSITIVITY', 'HIGHLY_SENSITIVITY'), ('ELECTRONIC', 'ELECTRONIC')], max_length=20)),
                ('whom_to_deliver', models.CharField(max_length=100)),
            ],
        ),
    ]
