# Generated by Django 2.2.1 on 2020-07-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0003_assettransportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransportrequest',
            name='others',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
