# Generated by Django 2.2.1 on 2020-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='profile_pic_url', max_length=200),
        ),
    ]
